/// A generated multiple-choice trivia question — used for the "Bible
/// characters and facts" quiz mode, graded locally (objective/factual, no
/// need to round-trip through the AI again).
class TriviaQuestion {
  TriviaQuestion({required this.question, required this.choices, required this.correctIndex});
  final String question;
  final List<String> choices;
  final int correctIndex;
}

/// Thrown when a provider call fails (bad/missing key, network, quota, or an
/// unparseable response) — callers surface [message] directly to the user.
class AiClientException implements Exception {
  AiClientException(this.message);
  final String message;
  @override
  String toString() => message;
}

/// Common interface both providers implement, so the quiz layer never cares
/// which one is active — only Settings and the "generated by" chip do.
abstract class AiClient {
  Future<TriviaQuestion> generateTrivia();

  /// One thought-provoking question testing whether you understood the
  /// lesson in your own note — never the note text verbatim, so it works
  /// even if the note itself is short.
  Future<String> generateLessonQuestion(String noteText);

  /// Judges a free-text answer against the original note/question — this is
  /// the "AI evaluates your work" step, not a local string match.
  Future<bool> gradeLessonAnswer({
    required String noteText,
    required String question,
    required String userAnswer,
  });
}
